"""
Django settings for rh_django project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
import pymysql
import dj_database_url
from dotenv import load_dotenv

# Cargar variables de entorno desde el archivo .env
load_dotenv()

pymysql.version_info = (2, 2, 2, "final", 0)
pymysql.install_as_MySQLdb()

BASE_DIR = Path(__file__).resolve().parent.parent

# Ahora leemos la clave secreta y el modo debug desde el .env
SECRET_KEY = os.environ.get('SECRET_KEY')
DEBUG = os.environ.get('DEBUG') == 'True'

# Aquí pondremos el dominio que nos dé el servidor (ej: 'mi-api.onrender.com')
ALLOWED_HOSTS = ['*'] # El asterisco permite cualquiera temporalmente, lo cambiaremos luego


# Application definition

INSTALLED_APPS = [
    #Corsheaders para permitir solicitudes desde el frontend
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Aplicaciones de terceros
    'rest_framework',
    # Aplicaciones propias
    'empleados',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', # Debe ir antes del CommonMiddleware
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'rh_django.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'rh_django.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

#---MySql (PyMySQL)---
DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.mysql',
    #     'NAME': 'recursos_humanos_db',
    #     'USER': 'root',
    #     'PASSWORD': 'admin',
    #     'HOST': '127.0.0.1',
    #     'PORT': '3306',
    #     'OPTIONS':{
    #         'charset': 'utf8mb4',
    #         'init_command': "SET sql_mode='STRICT_ALL_TABLES'",
    #     },
    #     'CONN_MAX_AGE': 60,  # Mantener la conexión abierta por 60 segundos  
    # }
    'default': dj_database_url.config(
        conn_max_age=600
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-es'

TIME_ZONE = 'America/Caracas'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# NUEVO: Le decimos a Django dónde guardar los archivos estáticos en producción
STATIC_ROOT = BASE_DIR / 'staticfiles'

# --- CONFIGURACIÓN CORS ---
CORS_ALLOWED_ORIGINS = [
    "https://frontend-rh-react-tu-usuario.vercel.app", # La de Vercel
    "http://localhost:4200", # Angular
    "http://localhost:5173", # React Vite
]

#Esto es opcional, pero puede ser útil para depuración, son los metodos HTTP permitidos en las solicitudes CORS

CORS_ALLOWED_METHODS = [
    "GET",
    "POST",
    "PUT",
    "PATCH",
    "DELETE",
    "OPTIONS",
]

#No forzar slash final
APPEND_SLASH = False